[build]
  command = "prisma generate && prisma db push --accept-data-loss && prisma db seed && npm run build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "file:./dev.db"

[[plugins]]
  package = "@netlify/plugin-nextjs"
